version: "3.8"

services:
  # restapi:
  #   image: ghcr.io/michelegennari/progettowebapi:main
  #   env_file:
  #     - ./.env.compose
  #   environment:
  #     MONGO_USER_FILE: /run/secrets/mongo_user
  #     MONGO_PW_FILE: /run/secrets/mongo_pw
  #     PROTOCOL: ${API_PROTOCOL:-http}
  #     HOSTNAME: ${API_HOSTNAME:-localhost}
  #     PORT: ${API_PORT:-8080}
  #     MONGO_HOSTNAME: ${MONGO_HOSTNAME:-mongodb}
  #     MONGO_PORT: ${MONGO_PORT:-27017}
  #   restart: on-failure
  #   depends_on: [mongodb]
  #   networks:
  #     - selfie
  #   ports:
  #     - ${API_PORT:-8080}:${API_PORT:-8080}
  #   secrets:
  #     - mongo_user
  #     - mongo_pw

  mongodb:
    restart: on-failure
    image: mongo
    env_file:
      - ./.env.compose
      - ./.env
      - ./.env.local
      - ./.env.development
      - ./.env.development.local
    expose:
      - ${DB_PORT:-27017}
    ports:
      - ${DB_PORT:-27017}:${DB_PORT:-27017}

secrets:
  mongo_user:
    file: ./secrets/mongo_user.txt
  mongo_pw:
    file: ./secrets/mongo_pw.txt
