name: CI/CD
run-name: CI/CD workflow run by ${{github.actor}}
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm run build --if-present
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    environment: ercolani
    steps:
      - name: ssh connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PW }}
          script: whoami

