name: Main PRs integration test
run-name: Integration test started by ${{github.actor}}
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version:
      - run: npm run build --if-present
      - run: npm test
